# Generated by Django 3.2.16 on 2022-10-27 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('Post', models.CharField(max_length=200)),
                ('Pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Capacity', models.IntegerField()),
                ('Type', models.CharField(max_length=200)),
                ('Details', models.CharField(max_length=200)),
                ('Cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('Post', models.CharField(max_length=200)),
                ('Pin', models.IntegerField()),
                ('Email', models.CharField(max_length=200)),
                ('Photo', models.CharField(max_length=200)),
                ('PhoneNo', models.IntegerField()),
                ('USERID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tourism.login')),
            ],
        ),
        migrations.CreateModel(
            name='travelers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('Post', models.CharField(max_length=200)),
                ('Pin', models.IntegerField()),
                ('Email', models.CharField(max_length=200)),
                ('Photo', models.CharField(max_length=200)),
                ('PhoneNo', models.IntegerField()),
                ('TRAVELID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tourism.login')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('USERID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tourism.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaints', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('replay', models.CharField(max_length=200)),
                ('Rdate', models.DateField()),
                ('USERID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tourism.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=200)),
                ('USERID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tourism.user')),
                ('VEHICLEID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tourism.vehicle')),
            ],
        ),
    ]
