# Generated by Django 3.2.16 on 2022-10-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='Rdate',
            new_name='Replay_date',
        ),
        migrations.AlterField(
            model_name='complaints',
            name='USERID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tourism.login'),
        ),
    ]
