# Generated by Django 3.2.16 on 2022-10-27 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0003_alter_complaints_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='TRAVELERID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tourism.travelers'),
            preserve_default=False,
        ),
    ]
