# Generated by Django 3.2.16 on 2022-10-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0005_rename_travelerid_vehicle_travelid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='TRAVELID',
        ),
    ]
