# Generated by Django 3.2.16 on 2022-11-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0006_remove_vehicle_travelid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='TRAVELID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tourism.travelers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='PhoneNo',
            field=models.BigIntegerField(),
        ),
    ]
