# Generated by Django 3.2.16 on 2022-11-18 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0007_auto_20221115_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='replay',
            new_name='Reply',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='Replay_date',
            new_name='Reply_date',
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.CharField(max_length=200)),
                ('USERID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tourism.login')),
            ],
        ),
    ]
